#!/bin/sh

ansible_command="$1"
shift

cmd="docker run --rm -it -v $(pwd):/ansible/project"

# ssh support
[ -f ~/.ssh/id_rsa ] && [ -f ~/.ssh/id_rsa.pub ] && \
    cmd="${cmd} -v ~/.ssh/id_rsa:/root/.ssh/id_rsa -v ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub"

# aws support
[ -f ~/.aws/credentials ] && \
    cmd="${cmd} -v ~/.aws/credentials:/root/.aws/credentials"
[ -f ~/.boto ] && \
    cmd="${cmd} -v ~/.boto:/root/.boto"

# vault password support
[ -f ~/.ansible/vault.pass ] && \
    cmd="${cmd} -v ~/.ansible/vault.pass:/root/vault.pass" && \
    ansible_command="${ansible_command} --vault-id /root/vault.pass"

# pems volume support
[ ! -z $(docker volume ls --filter 'name=pems_volume' -q) ] && \
    cmd="${cmd} -v pems_volume:/pems"

# inventory volume support
[ ! -z $(docker volume ls --filter 'name=inventory_volume' -q) ] && \
    cmd="${cmd} -v inventory_volume:/inventory"

cmd="${cmd} feydan/docker-ansible ${ansible_command} ${@}"

eval $cmd