#!/bin/sh

ansible_command="$1"
shift

docker run --rm -it \
  -v ~/.ssh/id_rsa:/root/.ssh/id_rsa \
  -v ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub \
  -v ~/.aws/credentials:/root/.aws/credentials \
  -v pems_volume:/pems \
  -v inventory_volume:/inventory \
  -v $(pwd):/ansible/project \
  -v /var/log/ansible/ansible.log \
  feydan/ansible "$ansible_command" "$@"